Update pom file
nipun-gupta-e3183/jesque pull request #1
Opened 2021-05-26 12:54 UTC by nipun-gupta-e3183

2021-05-26 14:55 UTC, tmkarthi requested changes

2021-05-26 14:55 UTC, tmkarthi commented on pom.xml
> +    <groupId>com.github.nipun</groupId>
```suggestion
    <groupId>com.github.nipun-gupta-e3183</groupId>
```

2021-05-26 14:55 UTC, tmkarthi commented on pom.xml
> +            <url>https://nexuscentral.runwayci.com/repository/maven-snapshots/</url>
Please don't add our internal infra details in a public repo.

2021-05-27 11:57 UTC, tmkarthi approved these changes

2021-05-28 12:04 UTC, tejo-kumar-E3481 approved these changes

2021-05-28 12:08 UTC, merged